\c wiki; 

INSERT INTO authors
	(fname, lname, full_name, created_at, email, password, phone_number, img)
VALUES
	('Jane', 'Doe', 'Jane Doe', CURRENT_TIMESTAMP, 'example@example.com', 'password1', '(555)-555-5555)', 'http://exmoorpet.com/wp-content/uploads/2012/08/cat.png'), 
	('John', 'Doe', 'John Doe', CURRENT_TIMESTAMP, 'example@example.com','password2', '(555)-555-5555)','https://pbs.twimg.com/profile_images/378800000532546226/dbe5f0727b69487016ffd67a6689e75a.jpeg'),
	('Jill','Frank', 'Jill Frank', CURRENT_TIMESTAMP, 'example@example.com','password3', '(555)-555-5555)', 'http://extension.unh.edu/sites/default/files/images/4HAnSci/inquisitive-cat300.png'),
	('James', 'Frank', 'James Frank', CURRENT_TIMESTAMP, 'example@example.com','password4', '(555)-555-5555)', 'http://www.helpinghomelesscats.com/images/cat.jpg'),
	('Janet', 'Doe', 'Jane Doe', CURRENT_TIMESTAMP, 'example@example.com','password5', '(555)-555-5555)', 'http://www.popkitten.com/wp-content/uploads/2011/12/Sad-Cat-8.jpg'), 
	('Henrietta', 'Frank', 'Henrietta Frank', CURRENT_TIMESTAMP, 'example@example.com','password5', '(555)-555-5555)', 'http://img1.wikia.nocookie.net/__cb20140619110546/adventuretimewithfinnandjake/images/6/64/Cat_with_glasses_10_262133k-1-.jpg')
	;

INSERT INTO categories
	(name)
VALUES
	('Millenials'),
	('Social Media'),
	('Work'),
	('Healthy Living'),
	('Marketing'),
	('Best Practices')
	; 

INSERT INTO articles
	(headline, body, created_at, updated, summary, category_id, author_id)
VALUES
	('The Rise of Youth Nation and How to Use Instagram to Reach Millenials', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas, velit quis imperdiet egestas, sem ex molestie leo, convallis tristique diam enim eget arcu. Maecenas accumsan sapien sit amet gravida eleifend. Quisque finibus ligula quam, vitae scelerisque lectus luctus quis. Mauris vitae facilisis enim. Praesent hendrerit eget mauris at finibus. Integer dictum, tellus non lacinia egestas, leo enim suscipit ante, id dignissim odio odio eu urna. Integer vel nulla eget sem euismod mattis in et dui. Vestibulum porttitor odio at nisl pharetra laoreet.Nunc quam libero, pellentesque id pretium in, eleifend a ipsum. Phasellus vel varius odio. Morbi in pretium odio. **Curabitur condimentum convallis vestibulum. Sed lobortis tellus quis elementum auctor. Fusce mollis ante suscipit vulputate finibus. Maecenas tempor lorem leo, ac cursus mi pulvinar quis. Ut cursus sit amet velit et condimentum. Aliquam neque nunc, auctor a purus vel, elementum rutrum nulla. Phasellus malesuada, lacus at auctor suscipit, turpis leo scelerisque nisi, vitae efficitur nulla tortor eget urna. Nullam eget orci risus.** In hac habitasse platea dictumst. Etiam ut imperdiet orci, sed lacinia elit. Morbi auctor nulla a condimentum sodales. Pellentesque sit amet efficitur massa. Aenean convallis pellentesque justo et ultrices. Suspendisse ornare lorem in odio ullamcorper, pharetra faucibus nisi pulvinar.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Instagram iz hard', 1, 1 ),
	('The Coolest Social Network With Teens', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas, velit quis imperdiet egestas, sem ex molestie leo, convallis tristique diam enim eget arcu. Maecenas accumsan sapien sit amet gravida eleifend. Quisque finibus ligula quam, vitae scelerisque lectus luctus quis. Mauris vitae facilisis enim. Praesent hendrerit eget mauris at finibus. *Integer dictum, tellus non lacinia egestas, leo enim suscipit ante, id dignissim odio odio eu urna. Integer vel nulla eget sem euismod mattis in et dui. Vestibulum porttitor odio at nisl pharetra laoreet.Nunc quam libero, pellentesque id pretium in, eleifend a ipsum. Phasellus vel varius odio. Morbi in pretium odio. Curabitur condimentum convallis vestibulum. Sed lobortis tellus quis elementum auctor. Fusce mollis ante suscipit vulputate finibus.* Maecenas tempor lorem leo, ac cursus mi pulvinar quis. Ut cursus sit amet velit et condimentum. Aliquam neque nunc, auctor a purus vel, elementum rutrum nulla. Phasellus malesuada, lacus at auctor suscipit, turpis leo scelerisque nisi, vitae efficitur nulla tortor eget urna. Nullam eget orci risus. In hac habitasse platea dictumst. Etiam ut imperdiet orci, sed lacinia elit. Morbi auctor nulla a condimentum sodales. Pellentesque sit amet efficitur massa. Aenean convallis pellentesque justo et ultrices. Suspendisse ornare lorem in odio ullamcorper, pharetra faucibus nisi pulvinar.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'It is not Myspace', 2, 2),
	('How to Get Great Content From Your Colleagues: Five Rules for Success', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas, velit quis imperdiet egestas, sem ex molestie leo, convallis tristique diam enim eget arcu. Maecenas accumsan sapien sit amet gravida eleifend. Quisque finibus ligula quam, vitae scelerisque lectus luctus quis. Mauris vitae facilisis enim. Praesent hendrerit eget mauris at finibus. Integer dictum, tellus non lacinia egestas, leo enim suscipit ante, id dignissim odio odio eu urna. Integer vel nulla eget sem euismod mattis in et dui. Vestibulum porttitor odio at nisl pharetra laoreet.Nunc quam libero, pellentesque id pretium in, eleifend a ipsum. Phasellus vel varius odio. Morbi in pretium odio. Curabitur condimentum convallis vestibulum. Sed lobortis tellus quis elementum auctor. >Fusce mollis ante suscipit vulputate finibus. Maecenas tempor lorem leo, ac cursus mi pulvinar quis. Ut cursus sit amet velit et condimentum. Aliquam neque nunc, auctor a purus vel, elementum rutrum nulla. Phasellus malesuada, lacus at auctor suscipit, turpis leo scelerisque nisi, vitae efficitur nulla tortor eget urna. Nullam eget orci risus. In hac habitasse platea dictumst. Etiam ut imperdiet orci, sed lacinia elit. Morbi auctor nulla a condimentum sodales. Pellentesque sit amet efficitur massa. > Aenean convallis pellentesque justo et ultrices. Suspendisse ornare lorem in odio ullamcorper, pharetra faucibus nisi pulvinar.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'"You wanna live fancy? Live in a big mansion? Party in France? You better work bitch" - *Britney Spears*', 3, 3 ),
	('Eight Tips to Help You Combat Procrastination Right Away', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas, velit quis imperdiet egestas, sem ex molestie leo, convallis tristique diam enim eget arcu. Maecenas accumsan sapien sit amet gravida eleifend. >**Quisque finibus ligula quam, vitae scelerisque lectus luctus quis. Mauris vitae facilisis enim. Praesent hendrerit eget mauris at finibus. Integer dictum, tellus non lacinia egestas, leo enim suscipit ante, id dignissim odio odio eu urna. Integer vel nulla eget sem euismod mattis in et dui. Vestibulum porttitor odio at nisl pharetra laoreet.Nunc quam libero, pellentesque id pretium in, eleifend a ipsum. Phasellus vel varius odio. Morbi in pretium odio.**> Curabitur condimentum convallis vestibulum. Sed lobortis tellus quis elementum auctor. Fusce mollis ante suscipit vulputate finibus. Maecenas tempor lorem leo, ac cursus mi pulvinar quis. Ut cursus sit amet velit et condimentum. Aliquam neque nunc, auctor a purus vel, elementum rutrum nulla. Phasellus malesuada, lacus at auctor suscipit, turpis leo scelerisque nisi, vitae efficitur nulla tortor eget urna. Nullam eget orci risus. In hac habitasse platea dictumst. Etiam ut imperdiet orci, sed lacinia elit. Morbi auctor nulla a condimentum sodales. Pellentesque sit amet efficitur massa. Aenean convallis pellentesque justo et ultrices. Suspendisse ornare lorem in odio ullamcorper, pharetra faucibus nisi pulvinar.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'I will write this later.', 4, 4),
	('2 Million Blog Posts Are Written Every Day, Here is How You Can Stand Out', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas, velit quis imperdiet egestas, sem ex molestie leo, convallis tristique diam enim eget arcu. Maecenas accumsan sapien sit amet gravida eleifend. Quisque finibus ligula quam, vitae scelerisque lectus luctus quis. Mauris vitae facilisis enim. Praesent hendrerit eget mauris at finibus. Integer dictum, tellus non lacinia egestas, leo enim suscipit ante, id dignissim odio odio eu urna. Integer vel nulla eget sem euismod mattis in et dui. Vestibulum porttitor odio at nisl pharetra laoreet.Nunc quam libero, pellentesque id pretium in, eleifend a ipsum. Phasellus vel varius odio. **Morbi in pretium odio.** Curabitur condimentum convallis vestibulum. Sed lobortis tellus quis elementum auctor. Fusce mollis ante suscipit vulputate finibus. Maecenas tempor lorem leo, ac cursus mi pulvinar quis. Ut cursus sit amet velit et condimentum. Aliquam neque nunc, auctor a purus vel, elementum rutrum nulla. Phasellus malesuada, lacus at auctor suscipit, turpis leo scelerisque nisi, vitae efficitur nulla tortor eget urna. Nullam eget orci risus. In hac habitasse platea dictumst. Etiam ut imperdiet orci, sed lacinia elit. Morbi auctor nulla a condimentum sodales. Pellentesque sit amet efficitur massa. Aenean convallis pellentesque justo et ultrices. Suspendisse ornare lorem in odio ullamcorper, pharetra faucibus nisi pulvinar.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Do not write a blog post.', 5, 5 ),
	('Avoid Infringement Troubles: Six Ways to Simplify Digital Rights Management', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas, velit quis imperdiet egestas, sem ex molestie leo, convallis tristique diam enim eget arcu. Maecenas accumsan sapien sit amet gravida eleifend. Quisque finibus ligula quam, vitae scelerisque lectus luctus quis. Mauris vitae facilisis enim. *Praesent hendrerit eget mauris at finibus. Integer dictum, tellus non lacinia egestas, leo enim suscipit ante, id dignissim odio odio eu urna. Integer vel nulla eget sem euismod mattis in et dui. Vestibulum porttitor odio at nisl pharetra laoreet.Nunc quam libero, pellentesque id pretium in, eleifend a ipsum. Phasellus vel varius odio. Morbi in pretium odio. *Curabitur condimentum convallis vestibulum. Sed lobortis tellus quis elementum auctor. Fusce mollis ante suscipit vulputate finibus. Maecenas tempor lorem leo, ac cursus mi pulvinar quis. Ut cursus sit amet velit et condimentum. Aliquam neque nunc, auctor a purus vel, elementum rutrum nulla. Phasellus malesuada, lacus at auctor suscipit, turpis leo scelerisque nisi, vitae efficitur nulla tortor eget urna. Nullam eget orci risus. In hac habitasse platea dictumst. Etiam ut imperdiet orci, sed lacinia elit. Morbi auctor nulla a condimentum sodales. Pellentesque sit amet efficitur massa. Aenean convallis pellentesque justo et ultrices. Suspendisse ornare lorem in odio ullamcorper, pharetra faucibus nisi pulvinar.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'I only stole headlines, not articles ...', 6, 6)
	;

